name: 'WebSentry Action'
description: 'Check the health of a website and report status'

inputs:
  website-url:
    description: 'The URL of the website to check (e.g., example.com)'
    required: true
  max-retries:
    description: 'Maximum number of retries (default: 3)'
    required: false
    default: '3'
  retry-interval:
    description: 'Time to wait between retries in seconds (default: 5)'
    required: false
    default: '5'
  request-timeout:
    description: 'Request timeout in seconds (default: 10)'
    required: false
    default: '10'

branding:
  icon: 'activity'
  color: 'gray-dark'

outputs:
  health-status:
    description: 'The health status of the website (up or down)'

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'  # Use the Go version you need

    - name: Run Check
      run: go run ${{ github.action_path }}/main.go -site ${{ inputs.website-url }} -maxretries ${{ inputs.max-retries}} -retryinterval ${{ inputs.retry-interval }} -requesttimeout ${{ inputs.request-timeout}}
      shell: bash