name: 'WebSentry Action'
description: 'Check the health of a website and report status'

inputs:
  website-url:
    description: 'The URL of the website to check (e.g., example.com)'
    required: true
  max-retries:
    description: 'Maximum number of retries (default: 3)'
    required: false
    default: '3'
  retry-interval:
    description: 'Time to wait between retries in seconds (default: 5)'
    required: false
    default: '5'

outputs:
  health-status:
    description: 'The health status of the website (up or down)'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16' # Use the Go version you need

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Websentry
      run: go run main.go ${{ inputs.website-url }} ${{ inputs.max-retries }} ${{ inputs.retry-interval }} ${{ inputs.request-timeout }}

branding:
  icon: 'shield'
  color: 'green'

