on: push

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License Check
    steps:
      - uses: actions/checkout@v2
      - uses: theritikchoure/websentry@main
        with:
          website-url: 'google.com'  # Set the website URL you want to check
          max-retries: 10
          retry-interval: 5
          request-timeout: 10
