name: Website Health Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes (adjust the cron schedule as needed)

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Website Health
        uses: theritikchoure/websentry@v1.3.0
        with:
          website-url: 'https://example.com'
          max-retries: 3
          retry-interval: 5
          request-timeout: 10
