on: push

jobs:
  website-health-check:
    runs-on: ubuntu-latest
    name: Website health check
    steps:
      - uses: actions/checkout@v2
      - uses: theritikchoure/websentry@main
        with:
          website-url: 'google.com,youtube.com'  # Set the website URL you want to check
          max-retries: '10'
          retry-interval: '5s'
          request-timeout: '10s'
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      -name: Deploy Documentation
        run: |
          touch report.pdf
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add report.pdf
          git commit -m "Auto-generate documentation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}